export const actionTypes = {
  SET_TOP_RATED_MOVIES: "SET_TOP_RATED_MOVIES",
  SET_ACTION_MOVIES: "SET_ACTION_MOVIES",
  SET_COMEDY_MOVIES: "SET_COMEDY_MOVIES",
  SET_NETFLIX_ORIGINALS: "SET_NETFLIX_ORIGINALS",
};
